### ISSUE TITLE
Regarding Extracting data and weights. Can't access pan baidu links outside china. Is it possible to share weights in drive links

### ISSUE THREAD

**Issue by Nithyan20** [SpursLipu/YOLOv3v4-ModelCompression-MultidatasetTraining-Multibackbone#103]

**Comment by walzimmer** [comment]
Can someone please upload the YoloV4 weights trained on VisDrone2020 on Google Drive or wetransfer.com?

These one can only be downloaded from China:
https://pan.baidu.com/s/1zOFyt_AFiNk0fAFa8yE9RQ
Extract code：xblu

**Comment by SpursLipu** [comment]
please send e-mail(spurslipu@pku.edu.cn) to me,
