### ISSUE TITLE
prune后mAP直接为0

### ISSUE THREAD

**Issue by Biubiubiu12** [SpursLipu/YOLOv3v4-ModelCompression-MultidatasetTraining-Multibackbone#118]
python3 normal_prune.py --cfg cfg/yolov3/yolov3-hand.cfg --data data/oxfordhand.data --weights weights/best.pt --percent 0.5 
+------------+----------+----------+
| Metric     | Before   | After    |
+------------+----------+----------+
| mAP        | 0.764819 | 0.000000 |
| Parameters | 61523734 | 21907584 |
| Inference  | 0.0902   | 0.0658   |
+------------+----------+----------+
second step --s 0.001,将稀疏后的best.pt进行裁剪后，mAP为0
我将percent缩小至0.1,仍然不起作用

**Comment by MohamedElsaeidy** [comment]
@Biubiubiu12  i have same issue could you solve ?

**Comment by Biubiubiu12** [comment]
must spare train before pruning



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月27日(周二) 晚上8:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SpursLipu/YOLOv3v4-ModelCompression-MultidatasetTraining-Multibackbone] prune后mAP直接为0 (#118)




 
@Biubiubiu12  i have same issue could you solve ?
