### ISSUE TITLE
自己跑的VisDrone数据和你相差过大

### ISSUE THREAD

**Issue by Zigars** [SpursLipu/YOLOv3v4-ModelCompression-MultidatasetTraining-Multibackbone#128]
我使用最新的yolov5x，image_size=1280, batch_size=8, epoch=100, 其它超参数都是默认的超参数配置，还使用了yolov5x预训练权重，但是我的最终mAP@.5:.95只有0.35, 但是你的yolov4默认配置就可以跑到0.438, 这是因为我们计算mAP的方式不一样嘛。。？
我用的是VisDrone2019-DET,是github官方网址下载的，用的是默认的train和val，我的yolov4在640分辨率的情况下只能和你的yolov4-tiny的数据差不多，在0.22左右，是因为我的conf设置的比较低嘛？不是很理解，最近在做相关的实验，看到了你的实验结果心里是有点小崩溃。。

**Comment by sudospike** [comment]
@Zigars ，你好能加个联系方式吗，想了解一下visdrone在一些方法上的的基准性能，我做了一些相关的实验
