### ISSUE TITLE
训练时测试精度，比最后保存的best.pt的精度要高。

### ISSUE THREAD

**Issue by chenjunson** [SpursLipu/YOLOv3v4-ModelCompression-MultidatasetTraining-Multibackbone#47]
训练时测试精度，显示已经到了91。但是我对最后保存的best.pt就行测试时模型精度确只有88%。

**Comment by SpursLipu** [comment]
你的参数设置和test一样吗？比如conf阈值 imgsize等

**Comment by chenjunson** [comment]
对比了test.py里面的上下两个部分的conf_thres=0.001和 iou_thres=0.6，数值都是一样的，那个 imgsize好像不一样，有个是416,有个是512,不过这都是默认设置，我没有去改过

**Comment by SpursLipu** [comment]
imagesize不一样的话测出来是不一样的

**Comment by chenjunson** [comment]
而且还有个奇怪的地方，我那个best.pt精度只有88,但是那个last.pt反而有89%

**Comment by chenjunson** [comment]
而且还有个奇怪的地方，我那个best.pt精度只有88,但是那个last.pt反而有89%
