### ISSUE TITLE
torch.nn.modules.module.ModuleAttributeError: 'YOLOLayer' object has no attribute 'grid'

### ISSUE THREAD

**Issue by mlbo** [SpursLipu/YOLOv3v4-ModelCompression-MultidatasetTraining-Multibackbone#51]
python train.py -pt --weights weights/yolov4-tiny.weights --cfg cfg/yolov4tiny/yolov4-tiny.cfg --device 0,1 --img-size 1024
![image](https://user-images.githubusercontent.com/29347606/89480376-be561e00-d7c7-11ea-8fca-1137d54e6467.png)

**Comment by SpursLipu** [comment]
你试试用CUDA_VISIBLE_DEVICES选择多卡训练

**Comment by ghm666** [comment]
我也遇到了这个问题

**Comment by kust-yhk** [comment]
请问如何解决，我也遇到了这个问题

**Comment by kust-yhk** [comment]
请问如何解决，我也遇到了这个问题

**Comment by SpursLipu** [comment]
你们用的指令是什么？

**Comment by ghm666** [comment]
> 你们用的指令是什么？

python train.py --data steel_data_cfg/steel.data    --batch-size 4   --weights weights/darknet53.conv.74  --cfg steel_data_cfg/yolov3-darknet53.cfg   --epochs  3    --t_cfg  steel_data_cfg/yolov3-darknet53.cfg   --t_weights  weights/yolov3-darknet53_best.pt  --KDstr 1

**Comment by kust-yhk** [comment]
> 你们用的指令是什么？

python3 train.py --data data/obj.data --batch-size 4 -pt --weights weights/yolov3-mobilenet.weights --cfg cfg/yolov3-mobilenet/yolov3-mobilenet-coco.cfg --epochs 600

**Comment by SpursLipu** [comment]
最新更新这个问题应该已经解决了

**Comment by TaoZhang1993** [comment]
我这边用coco2017的数据去训练，在Caching images的时候，会出现内存爆炸(16G内存)，这个问题请问有解决吗？

**Comment by SpursLipu** [comment]
你试试先把所有的cache_images都改成False吧，先把这个关了，后面我再看下

**Comment by TaoZhang1993** [comment]
test的设置成False也会Caching images
