### ISSUE TITLE
可以增加mobilenetv2么

### ISSUE THREAD

**Issue by anguoyang** [SpursLipu/YOLOv3v4-ModelCompression-MultidatasetTraining-Multibackbone#57]
测试过人脸检测（retinaface/pytorch），mobilenetv3（即便是large）的精度不如mobilenetv2,而且差的还比较多。不知道yolov4怎么样。当然v2的确比较大

**Comment by SpursLipu** [comment]
你可以自己改吧mobilenet的算子，我这个仓库都支持的，你只需要重新写cfg文件就可以了

**Comment by anguoyang** [comment]
好的，谢谢
