### ISSUE TITLE
yolov3-dior-best.weights

### ISSUE THREAD

**Issue by Vlad15lav** [SpursLipu/YOLOv3v4-ModelCompression-MultidatasetTraining-Multibackbone#60]
嘿。我正在为Dior YOLOv3-640数据集使用经过训练的权重。但我的平均估算值约为0.43，而不是0.749。
我的设置：
yolov3-onDIOR.cfg
图片尺寸608
可能是什么原因？

**Comment by SpursLipu** [comment]
我的是可以的啊，我用的指令是
python test.py --cfg cfg/yolov3/yolov3-onDIOR.cfg --data data/dior.data --weights weights/yolov3-dior-best.weights

**Comment by Vlad15lav** [comment]
不起作用。您是否更改了Dior数据集中的任何内容？我在OneDrive中使用官方文章中的套件。我无法从您的链接下载大型存档，也许还有另一个云？

**Comment by SpursLipu** [comment]
我这里也是可以下载的

**Comment by Vlad15lav** [comment]
Maybe, I have a problem with the data set. Your link only works in China. Can you send a different link to the Dior data set, not Baidu? Please.

**Comment by Vlad15lav** [comment]
The problem was solved. Thanks.
