### ISSUE TITLE
怎么关闭多尺度训练？我训练命令中没使用--multi-scale

### ISSUE THREAD

**Issue by Note-Liu** [SpursLipu/YOLOv3v4-ModelCompression-MultidatasetTraining-Multibackbone#73]

**Comment by Note-Liu** [comment]
是把min和max设置成一样吧

**Comment by SpursLipu** [comment]
不用--multi-scale就不会开多尺度训练啊 需要设置一下image-size

**Comment by Note-Liu** [comment]
使用默认的：
parser.add_argument('--img-size', nargs='+', type=int, default=[320, 640], help='[min_train, max-train, test]')
不用--multi-scale命令，训练过程中打印出来的imgsize也在变。

**Comment by SpursLipu** [comment]
你需要设置具体的imgsize 就可以了

**Comment by Note-Liu** [comment]
OK




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "SpursLipu"<notifications@github.com&gt;; 
发送时间: 2020年10月14日(星期三) 晚上9:33
收件人: "SpursLipu/YOLOv3v4-ModelCompression-MultidatasetTraining-Multibackbone"<YOLOv3v4-ModelCompression-MultidatasetTraining-Multibackbone@noreply.github.com&gt;; 
抄送: "缘 ✨"<2930597968@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [SpursLipu/YOLOv3v4-ModelCompression-MultidatasetTraining-Multibackbone] 怎么关闭多尺度训练？我训练命令中没使用--multi-scale (#73)





 
你需要设置具体的imgsize 就可以了
