### ISSUE TITLE
训练yolov4的时候，各项指标变成0

### ISSUE THREAD

**Issue by ly0303521** [SpursLipu/YOLOv3v4-ModelCompression-MultidatasetTraining-Multibackbone#90]
![Screenshot from 2020-11-18 13-30-25](https://user-images.githubusercontent.com/11954512/99487992-5f956880-29a2-11eb-8ef7-34e99f461753.png)
如图，训练yolov4的时候，出现各项指标都变成0的情况，请问时什么原因造成的

**Comment by ly0303521** [comment]
下面是我稀疏训练的命令
`python train.py --data missions/trash_lid_v4/trash_lid_v4.data \
                --batch-size 3 \
                -pt --weights pretrained/yolov4.weights \
                --cfg missions/trash_lid_v4/yolov4-custom_trash_lid.cfg \
                -sr --s 0.001 \
                --wdir weights_trash_lid_v4_p0 \
                --prune 0 \
                --device 3 \
                --img-size 608 \
                --adam`

**Comment by ly0303521** [comment]
下面是我稀疏训练的命令
python train.py --data missions/trash_lid_v4/trash_lid_v4.data \
                --batch-size 3 \
                -pt --weights pretrained/yolov4.weights \
                --cfg missions/trash_lid_v4/yolov4-custom_trash_lid.cfg \
                -sr --s 0.001 \
                --wdir weights_trash_lid_v4_p0 \
                --prune 0 \
                --device 3 \
                --img-size 608 \
                --adam

**Comment by SpursLipu** [comment]
你试试调小一下s 系数因子，看看有没有作用

**Comment by ly0303521** [comment]
@SpursLipu  把S系数调小之后有用的，谢谢
