### ISSUE TITLE
NameError: name 'FPGA' is not defined

### ISSUE THREAD

**Issue by chengyequn** [SpursLipu/YOLOv3v4-ModelCompression-MultidatasetTraining-Multibackbone#96]
您好，我在进行YOLOv3-mobilenet的训练时，出现以下错误：NameError: name 'FPGA' is not defined，发现load_darknet_weights函数调用时没有传入FPGA这个参数，在这个函数内部却有这个变量的使用，想请问以下这个参数的意思，是否需要在调用函数的时候把那个参数传递进去，期待您的回复

**Comment by SpursLipu** [comment]
bug已处理，这个参数在这个函数中没有什么用
